### ISSUE TITLE
Allow the user to set up a custom CA file

### ISSUE THREAD

**Issue by turetske** [xrootd/xrdcl-http#11]
The plugin ignored user set CA files.

Currently, even if the user sets up a CA file in their xrootd config using `xrd.tlsca certfile` or `xrd.tlsca certdir`, the plugin seems to use the system default files instead.

This probably would involve a fix similar to what was done in scitokens-cpp at this pull request: https://github.com/scitokens/scitokens-cpp/pull/132

**Comment by amadio** [comment]
Could you please file this issue in the xrootd/xrootd repository? This is an old repository used to develop the http plugin for the client, but not it's merged into the main repository and unused. Thank you!

**Comment by bbockelm** [comment]
@amadio -- is it possible to mark this repository as archived and leave an explanatory text in the README redirecting to `xrootd/xrootd` as you have above?  Will help out folks in the future.

**Comment by amadio** [comment]
My plan is to make it private once the ticket is in both places. Will do it tomorrow if it's not there yet.

**Comment by turetske** [comment]
@amadio Filed it at https://github.com/xrootd/xrootd/issues/2136

**Comment by amadio** [comment]
Thank you!
